### ISSUE TITLE
How do I change the default request timeout in a service definition?

### ISSUE THREAD

**Issue by codecowboy** [misd-service-development/guzzle-bundle#56]
I'd like to increase the default timeout of guzzle client requests. Can I add this in my service definition?

```
      mynamespace.client:
          class: %guzzle.client.class%
          arguments: [http://local.mynamespace-api]

          tags:
            - { name: guzzle.client }
```

If not, how do I configure / set / change this?
