### ISSUE TITLE
How do I set a proxy in yaml?

### ISSUE THREAD

**Issue by codecowboy** [misd-service-development/guzzle-bundle#60]
I would like to set a proxy on the following guzzle service:

```
      my.client:
          class: %guzzle.client.class%
          arguments: [%my_api_endpoint%,  { proxy: 'tcp://192.168.56.1:8888' }]

          tags:
            - { name: guzzle.client }
```

The docs only have XML config. How can I set this in yaml? The above does not seem to work
