### ISSUE TITLE
deSerialization partially broken on 1.1.5

### ISSUE THREAD

**Issue by alex-pex** [misd-service-development/guzzle-bundle#74]
Hi !

I used to describe my webservice with a custom response : an ArrayCollection of Entity

``` yaml
"getExams": {
    "httpMethod": "GET",
    "uri": "/api/exams.json",
    "additionalParameters": {
        "location": "query"
    },
    "responseClass":"ArrayCollection<MyApp\\ModelBundle\\Entity\\Exam>"
},
```

on 1.1.4 it was working (but it wasn't an ArrayCollection, just a simple array). On 1.1.5 it says Response must implement a fromCommand method. I don't think it detected it was a JMSSerializer @Type.

For the moment, I'll stick with 1.1.4 unless a fix is found
