### ISSUE TITLE
Cache plugin issues

### ISSUE THREAD

**Issue by COil** [misd-service-development/guzzle-bundle#88]
Hi, I am trying to use the cache plugin, I have activated in my config: ("misd/guzzle-bundle": "~1.0")

```
app.api.client:
    class: Guzzle\Service\Client
    arguments: [%api.base_url%, %api.defaults%]
    calls:
        - [setDefaultOption, ['headers/Accept', 'application/json']]
        - [addSubscriber, [@misd_guzzle.cache.filesystem]]
    tags:
        - {name: guzzle.client}
```

In my API I have added cache headers for a given url, when accessing this ressource, I get: (at 2nd call)

```
coil Guzzle/3.9.3 curl/7.35.0 PHP/5.5.9-1ubuntu4.9: - [2015-08-04T11:07:07+00:00] "GET /ref HTTP/1.1" 200 230177 (0 ms)
```

Which is OK, the response is returned from the cache, with 0ms.

But for all the other API calls where I didn't activated the cache, the request are run 2 times and the filesystem is growing even those responses are not supposed to be cached. And even the called API URLs are the same, the cache keeps and growing (+200ko at each request)

```
X-Cache-Lookup: HIT from GuzzleCache
X-Cache: MISS from GuzzleCache
```

Even if I only call the cached API url, the cache filesystem keeps on growing.

Any idea ? Bug or configuration problem ?
